# Generated by Django 4.2 on 2023-04-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_title_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('movie', 'Movies'), ('concerts', 'Concerts'), ('theatre', 'Theatre')], max_length=255),
        ),
    ]
