# Generated by Django 4.2 on 2023-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Movie', 'Movies'), ('Concerts', 'Concerts'), ('Theatre', 'Theatre')], max_length=255),
        ),
    ]
