# Generated by Django 4.2 on 2023-04-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster URL'),
        ),
    ]
