# Generated by Django 3.2 on 2023-05-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230502_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='quantity',
            new_name='tickets_quantity_dance_floor',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_quantity_seating_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_quantity_vip_zone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='has_vip_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('dance_floor', 'Dance Floor'), ('vip', 'VIP'), ('seating', 'Seating Area')], max_length=255),
        ),
    ]
