# Generated by Django 3.2 on 2023-05-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230502_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.ticket'),
        ),
    ]
