# Generated by Django 4.2 on 2023-04-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.CharField(default='soon.png', max_length=255, null=True, verbose_name='Poster URL'),
        ),
    ]
