# Generated by Django 3.2 on 2023-05-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_account_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_quantity_dance_floor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_quantity_seating_area',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_quantity_vip_zone',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tickets_quantity_dance_floor', models.IntegerField(default=0)),
                ('tickets_quantity_vip_zone', models.IntegerField(default=0)),
                ('tickets_quantity_seating_area', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.eventlocation'),
        ),
    ]
