# Generated by Django 3.2 on 2023-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_tickettype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(choices=[('dance_floor', 'Dance Floor'), ('vip', 'VIP'), ('seating', 'Seating Area')], max_length=255),
        ),
    ]
