# Generated by Django 3.2 on 2023-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Movies', 'Movies'), ('Concerts', 'Concerts'), ('Theatre', 'Theatre')], max_length=255, unique=True),
        ),
    ]
